name: flutter_asset_generator
description: Generates the resource file by scanning assets defined in the pubspec.yaml, imitation R file short name.
repository: https://github.com/freatraum/flutter_asset_generator
version: 1.2.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.7.0
  dart_style: ^3.1.0
  glob: ^2.1.3
  io: ^1.0.5
  path: ^1.9.1
  yaml: ^3.1.3

executables:
  ffgen: asset_generator
